dataset:
  name: partnet
  categories: [knife]
model:
  name: partonomic
  shape:
    init: ellipse
    scale: 0.4
    use_mean_txt: True
    direct_field:
      powers: [2, 8, 32]
      milestones: [261, 522, 783]
      n_field_units: 512 
      zero_last_init: False
    weights_field:
      powers: [2, 8, 32]
      milestones: [261, 522, 783]
      n_field_units: 512
      zero_last_init: True
  mesh:
    use_mean_txt: True
    texture_uv:
      powers: [2, 8, 32]
      milestones: [0, 261, 522]
    deform_field:
      powers: [2, 8, 32]
      milestones: [261, 522, 783]
      zero_last_init: True
      n_field_units: 128
  renderer:
    cameras:
      name: perspective
      focal_length: 3.732050895690918
    faces_per_pixel: 50
  rend_predictor:
    alternate_optim: True
    azim_range: [0, 360]
    elev_range: [30, 30]
    roll_range: [0, 0]
    T_range: [0.2, 0.2, 0]
    scale_range: [0.5, 0.5, 0.5]
  milestones:
    freeze_scale_predictor: 87
    constant_txt: 261
  loss:
    name: mse
    rgb_weight: 1
    mask_weight: 1
    part_weight: 1
    perceptual_weight: 10
    laplacian_weight: 0.01
    normal_weight: 0.01
    uniform_weight: 0.4
    swap_weight: 1
training:
  batch_size: 2
  n_workers: 4
  optimizer:
    name: adam
    lr: 1.0e-4
  scheduler:
    name: multi_step
    gamma: 0.2
    milestones: [1200]
  n_epoches: 1000
  save_epoches: [261, 522, 783]
  train_stat_interval: 2000
  val_stat_interval: 4000
  seed: 83978
  visualizer_port: 
  resume: 
