dataset:
  name: shapenet_part
  categories: [lamp]
model:
  name: unicorn
  shape:
    init: ellipse
    scale: 0.4
    use_mean_txt: True
    direct_field:
      powers: [2, 8, 32]
      milestones: [41, 82, 123]
      n_field_units: 512 
      zero_last_init: False
    weights_field:
      powers: [2, 8, 32]
      milestones: [41, 82, 123]
      n_field_units: 512
      zero_last_init: False
  mesh:
    use_mean_txt: True
    texture_uv:
      img_size: 64
      powers: [2, 8, 32, 128]
      milestones: [0, 41, 82, 123]
  renderer:
    cameras:
      name: perspective
      focal_length: 3.732050895690918
    faces_per_pixel: 50
  rend_predictor:
    alternate_optim: True
    azim_range: [0, 360]
    elev_range: [30, 30]
    roll_range: [0, 0]
    T_range: [0.2, 0.2, 0]
    scale_range: [0.5, 0.5, 0.5]
  milestones:
    freeze_scale_predictor: 8
    constant_txt: 41
  loss:
    name: mse
    rgb_weight: 1
    perceptual_weight: 10
    laplacian_weight: 0.01
    normal_weight: 0.01
    uniform_weight: 0.5
    swap_weight: 1
training:
  batch_size: 28
  n_workers: 4
  optimizer:
    name: adam
    lr: 1.0e-4
  scheduler:
    name: multi_step
    gamma: 0.2
    milestones: [156]
  n_epoches: 164
  save_epoches: [41, 82, 123]
  train_stat_interval: 2000
  val_stat_interval: 4000
  seed: 15557
  visualizer_port:
  resume: