dataset:
  name: shapenet_part
  categories: [car]
model:
  name: unicorn
  renderer:
    cameras:
      name: perspective
      focal_length: 3.732050895690918
    faces_per_pixel: 50
  rend_predictor:
    alternate_optim: True
    azim_range: [0, 360]
    elev_range: [30, 30]
    roll_range: [0, 0]
    T_range: [0.2, 0.2, 0]
    scale_range: [0.5, 0.5, 0.5]
training:
  batch_size: 28
  n_workers: 4
  optimizer:
    name: adam
    lr: 1.0e-4
  scheduler:
    name: multi_step
    gamma: 0.2
    milestones: [44]
  n_epoches: 48
  save_epoches: [12, 24, 36]
  train_stat_interval: 2000
  val_stat_interval: 4000
  seed: 48095
  visualizer_port: 
  resume: /mnt/sde1/xiaoqianruan/unicorn-main_2d_ground_truth/runs/shapenet_part/0531_car1/
  #resume: 