dataset:
  name: shapenet_part
  categories: [table]
model:
  name: unicorn
  shape:
    init: ellipse
    scale: 0.4
    use_mean_txt: True
    direct_field:
      powers: [2, 8, 32]
      milestones: [11, 22, 33]
      n_field_units: 512 
      zero_last_init: False
    weights_field:
      powers: [2, 8, 32]
      milestones: [11, 22, 33]
      n_field_units: 512
      zero_last_init: True
  mesh:
    use_mean_txt: True
    texture_uv:
      img_size: 64
      powers: [2, 8, 32, 128]
      milestones: [0, 11, 22, 33]
  renderer:
    cameras:
      name: perspective
      focal_length: 3.732050895690918
    faces_per_pixel: 50
  rend_predictor:
    alternate_optim: True
    azim_range: [0, 360]
    elev_range: [30, 30]
    roll_range: [0, 0]
    T_range: [0.2, 0.2, 0]
    scale_range: [0.5, 0.5, 0.5]
  milestones:
    freeze_scale_predictor: 2
    constant_txt: 10
  loss:
    name: mse
    #mask: mask
    rgb_weight: 1
    perceptual_weight: 10
    laplacian_weight: 0.01
    normal_weight: 0.01
    uniform_weight: 0.2
    swap_weight: 1
training:
  batch_size: 24
  n_workers: 4
  optimizer:
    name: adam
    lr: 1.0e-4
  scheduler:
    name: multi_step
    gamma: 0.2
    milestones: [40]
  n_epoches: 80
  save_epoches: [11, 22, 33]
  train_stat_interval: 2000
  val_stat_interval: 4000
  seed: 4602
  visualizer_port: 
  #resume:
  #resume: /mnt/sde1/xiaoqianruan/unicorn-main1/runs/shapenet_nmr/0226_table1/
  resume: /mnt/sde1/xiaoqianruan/unicorn-main_2d_ground_truth/runs/shapenet_part/0724_table1/
