dataset:
  name: cub_images
  img_size: 64
model:
  name: Partonomic_CUB
  shape:
    init: ellipse
    scale: 0.6
    use_mean_txt: True
    direct_field:
      powers: [2, 8, 32]
      milestones: [200, 400, 600]
      n_field_units: 512 
      zero_last_init: False
    weights_field:
      powers: [2, 8, 32]
      milestones: [200, 400, 600]
      n_field_units: 512
      zero_last_init: False
  mesh:
    use_mean_txt: True
    deform_field:
      powers: [2, 8, 32]
      milestones: [200, 400, 600]
      zero_last_init: True
    texture_uv:
      powers: [2, 8, 32]
      milestones: [0, 200, 400]
  renderer:
    cameras:
      name: fov
      fov: 30
  rend_predictor:
    alternate_optim: True
    azim_range: [0, 360]
    elev_range: [-10, 30]
    roll_range: [-30, 30]
    T_range: [0.3, 0.3, 0.3]
    scale_range: [0.3, 0.3, 0.3]
  milestones:
    freeze_T_predictor: 5
    freeze_shape: 10
    freeze_scale_predictor: 1200
    mean_txt: 600
  loss:
    name: mse
    rgb_weight: 1
    mask_weight: 1
    part_weight: 1
    perceptual_weight: 10
    laplacian_weight: 0.01
    normal_weight: 0.01
    uniform_weight: 0.4
    swap_weight: 1
training:
  batch_size: 32
  n_workers: 4
  optimizer:
    name: adam
    lr: 1.0e-4
  n_epoches: 1200
  save_epoches: [200, 400, 600]
  train_stat_interval: 2000
  val_stat_interval: 4000
  seed: 924674
  visualizer_port:
  resume: